config/routes.rb
Rails.application.routes.draw do
  resources :medical_certificates
  resources :personal_protection_entries
  resources :recipes
  resources :personal_protection_patients
  resources :personal_protections
  resources :company_processes
  resources :tasks
  resources :diagnostics
  resources :projects
  resources :commissions
  resources :work_centers
  resources :medical_services
  resources :risk_evaluations
  resources :risk_evaluation_risks
  resources :risks
  resources :risk_categories
  devise_for :users, controllers: { sessions: 'users/sessions' }
  match '/positions/diagram' => 'positions#diagram', :via => [:get, :post, :put]
  resources :medical_appointments do
    collection do
      get "today"
    end
  end
  resources :medical_records do
    collection do
      get "audits"
    end
    member do
      get "audit"
    end
  end
  resources :patient_records do 
    member do
      get "vaccines"
      get "recipes"
      get "laboratories"
      get "medical_history"
      get "medical_certificates"
    end
    resources :medical_checks do
      member do
        get "preview"
        get "result_file"
      end

    end
  end
  resources :medical_results, only: [:index, :show] do
    collection do
      get "distribution"
      get "diseases"
    end
  end
  resources :indicators, only: [:index] do
    collection do
      get "absenteeism"
    end
  end
  resources :medical_entries, only: [:index, :show, :new] do
    collection do
      get "register_values"
      get "list"
    end
  end
  resources :medical_profiles
  resources :exams
  resources :patients do
    collection do
      get "import_nl_patient"
      get "reports"
      get "print" 
    end
  end
  resources :areas
  resources :companies do
    collection do
      get "import_nl_source"
    end
  end
  resources :positions
  resources :users

  get 'risk_evaluations_details_dataset', to: 'risk_evaluations#get_dataset_details'
  get 'risk_evaluations_dataset', to: 'risk_evaluations#get_dataset'
  get 'risk_categories_dataset', to: 'risk_categories#get_dataset'
  get 'risks_dataset', to: 'risks#get_dataset'
  get 'projects_dataset', to: 'projects#get_dataset'
  get 'companies_dataset', to: 'companies#get_dataset'
  get 'commissions_dataset', to: 'commissions#get_dataset'
  get 'work_centers_dataset', to: 'work_centers#get_dataset'
  get 'exams_dataset', to: 'exams#get_dataset'
  get 'diagnostics_dataset', to: 'diagnostics#get_dataset'
  get 'personal_protections_dataset', to: 'personal_protections#get_dataset'
  get 'personal_protection_entries_dataset', to: 'personal_protection_entries#get_dataset'
  get 'positions_dataset', to: 'positions#get_dataset'
  get 'medical_profiles_dataset', to: 'medical_profiles#get_dataset'
  get 'patients_dataset', to: 'patients#get_dataset'
  get 'patient_records_dataset', to: 'patient_records#get_dataset'
  get 'medical_services_dataset', to: 'medical_services#get_dataset'
  get 'users_dataset', to: 'users#get_dataset'
  post 'save_current_company', to: 'companies#save_current_company'
  post 'get_exams_1', to: 'medical_profiles#get_exams_1'
  # Auto save methods
  post 'new_personal_history', to:'medical_records#new_personal_history'
  post 'remove_personal_history', to:'medical_records#remove_personal_history'

  root to: 'stack#index'
  get ':page' => 'stack#show', as: 'stack'

  mount ReportsKit::Engine, at: '/'
  
end

app/models/medical_certificate.rb
class MedicalCertificate < ApplicationRecord
	belongs_to :patient
	belongs_to :created_by, class_name: "User"
  belongs_to :company

  def id_to_s
    self.id.to_s.rjust(5, "0")
  end

  def self.print_data(medical_certificate)

  	pdf = Prawn::Document.new
  	title = "Certificado Médico"
  	
  	PdfTemplate.header(pdf, title)
  
    pdf.text "Datos Generales:", :style => :bold    
    pdf.move_down 20

    table_data = [
      ["<b>Médico:</b>", "#{medical_certificate.created_by.name}", "<b>Empresa:</b>", "#{medical_certificate.company.name}"], 
      ["<b>Trabajador:</b>", "#{medical_certificate.patient.full_name}", "<b>Fecha de Emisión:</b>", "#{medical_certificate.date}"],
      ["<b>Desde:</b>", "#{medical_certificate.starts_date}", "<b>Hasta:</b>", "#{medical_certificate.ends_date}"]
    ]

    pdf.table(table_data, :column_widths => [135, 135, 135, 135], :cell_style => { :inline_format => true }) do |t|
      t.cells.border_width = 1
    end

    pdf.move_down 20
    pdf.text "Diagnóstico:", :style => :bold
    pdf.text "#{medical_certificate.diagnostic_description}"

    pdf.render
  end


end

app/controllers/medical_certificates_controller.rb
class MedicalCertificatesController < ApplicationController
  before_action :set_medical_certificate, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @medical_certificates = MedicalCertificate.all
    respond_with(@medical_certificates)
  end



   def show
    respond_to do |f|
      f.html {respond_modal_with @medical_certificate}
      f.js {respond_modal_with @medical_certificate}
      f.pdf {send_data MedicalCertificate.print_data(@medical_certificate), filename:'receta.pdf', type: "application/pdf", disposition: :inline}
    end
  end

  def new
    @medical_certificate = MedicalCertificate.new
    @medical_certificate.patient_id = params[:patient_id] if params[:patient_id].present?
    @medical_certificate.created_by_id = current_user.id
    @medical_certificate.company_id = @company.id
    @medical_certificate.date = Time.now
    @medical_certificate.starts_date = Time.now
    @medical_certificate.ends_date = Time.now + 2.days
    @medical_certificate.days = 3
    @medical_certificate.medical_record_id = params[:medical_record_id] if params[:medical_record_id].present?
    respond_modal_with @medical_certificate
  end

  def edit
    respond_modal_with @medical_certificate
  end

  def create
    @medical_certificate = MedicalCertificate.create(medical_certificate_params)
    
    if @medical_certificate.medical_record_id.present?
      location = patient_record_medical_check_path(@medical_certificate.patient_id, @medical_certificate.medical_record_id)
    else
      location = medical_certificates_patient_record_path(@medical_certificate.patient_id)
    end

    respond_modal_with @medical_certificate, location: location
  end

  def update
    @medical_certificate.update(medical_certificate_params)

    
    respond_modal_with @medical_certificate, location: medical_certificates_patient_record_path(@medical_certificate.patient_id)
  end


  def destroy
    @medical_certificate.destroy
    respond_with(@medical_certificate)
  end

  private
    def set_medical_certificate
      @medical_certificate = MedicalCertificate.find(params[:id])
    end

    def medical_certificate_params
      params.require(:medical_certificate).permit(:date, :patient_id, :medical_record_id, :reason, :diagnostic_description, :days, :starts_date, :ends_date, :created_by_id, :document_id, :type_certificate, :company_id)
    end
end

app/helpers/medical_certificates_helper.rb
module MedicalCertificatesHelper
end

app/views/medical_certificates/_form.html.erb
<%= simple_form_for(@medical_certificate, remote: request.xhr?, html: { data: { modal: true } }) do |form| %>
  <div class="modal-body">
    <div class="row">

      
      <%= form.input :medical_record_id, :as => :hidden %>
    
      <%= form.input :patient_id, :as => :hidden %>
      <div class="col-md-6">
        <label class="form-control-label select required" for="patient_company_id">Trabajador <abbr title="required">*</abbr></label>
        <div class="company-label d-flex align-items-center mb-2">
            <i class="material-icons mr-1">person</i>
            <div class="text-body"><strong><%= @medical_certificate.patient.full_name %></strong></div>
        </div>
      </div>
      
      <%= form.input :company_id, :as => :hidden %>
      
      <div class="col-md-6">
        <label class="form-control-label select required" for="patient_company_id">Empresa <abbr title="required">*</abbr></label>
        <div class="company-label d-flex align-items-center mb-2">
            <i class="material-icons mr-1">business</i>
            <div class="text-body"><strong><%= @company.name %></strong></div>
        </div>
      </div>

      <div class="col-md-6">
        <%= form.input :date, as: :string , input_html: {class: 'date-selector'} %>
      </div>

      <%= form.input :created_by_id, :as => :hidden, :value => current_user.id %>

      <div class="col-md-6">
        <label class="form-control-label select required" for="patient_company_id">Médico <abbr title="required">*</abbr></label>
        <div class="company-label d-flex align-items-center mb-2">
            <i class="material-icons mr-1">account_box</i>
            <div class="text-body"><strong><%= current_user.name %></strong></div>
        </div>
      </div>

      <div class="col-md-6">
        <%= form.input :days %>
      </div>

      <div class="col-md-3">
        <%= form.input :starts_date, as: :string , input_html: {class: 'date-selector'} %>
      </div>

      <div class="col-md-3">
        <%= form.input :ends_date, as: :string , input_html: {class: 'date-selector'} %>
      </div>

      <div class="col-md-12">
        <%= form.input :diagnostic_description %>
      </div>

      <div class="form-inputs" style="display: none;">
        
        <%= form.input :reason %>
        <%= form.input :document_id %>
        <%= form.input :type_certificate %>
      </div>
      
    </div>
  </div>

  <div class="modal-footer">
    <%= render '/shared/dialog_buttons' %>
  </div>
<% end %>

<script type="text/javascript">
  $('select.select_2').select2({
    language: {
      noResults: function () {
        return "No se encontró resultados";
      }
    },
    placeholder: function(){
      $(this).data('placeholder');
    },
    containerCssClass: ':all:',
    theme: "bootstrap",
    dropdownParent: $('#modal .modal-body')
  });

  $("#url").val(window.location.pathname);

  $(".date-selector").flatpickr({
    altInput: true,
    enableTime: false,
    dateFormat: "Y-m-d",
  });
</script>

app/views/medical_certificates/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Editar Certificado Médico</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', medical_certificate: @medical_certificate %>

app/views/medical_certificates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medical Certificates</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Patient</th>
      <th>Medical record</th>
      <th>Reason</th>
      <th>Diagnostic description</th>
      <th>Days</th>
      <th>Starts date</th>
      <th>Ends date</th>
      <th>Created by</th>
      <th>Document</th>
      <th>Type certificate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_certificates.each do |medical_certificate| %>
      <tr>
        <td><%= medical_certificate.date %></td>
        <td><%= medical_certificate.patient_id %></td>
        <td><%= medical_certificate.medical_record_id %></td>
        <td><%= medical_certificate.reason %></td>
        <td><%= medical_certificate.diagnostic_description %></td>
        <td><%= medical_certificate.days %></td>
        <td><%= medical_certificate.starts_date %></td>
        <td><%= medical_certificate.ends_date %></td>
        <td><%= medical_certificate.created_by_id %></td>
        <td><%= medical_certificate.document_id %></td>
        <td><%= medical_certificate.type_certificate %></td>
        <td><%= link_to 'Show', medical_certificate %></td>
        <td><%= link_to 'Edit', edit_medical_certificate_path(medical_certificate) %></td>
        <td><%= link_to 'Destroy', medical_certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medical Certificate', new_medical_certificate_path %>

app/views/medical_certificates/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Nuevo Certificado Médico</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', medical_certificate: @medical_certificate %>

app/views/medical_certificates/show.html.erb
<div class="modal-header">
  <h5 class="modal-title">Certificado Médico</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <div class="row">
    <div class="col-md-3">
      
      <label style="font-size: 1rem;text-transform: uppercase; font-weight: bold;">
        Nombre:
      </label>
      <br/>
      <label style="font-size: 1rem;color: rgba(147, 159, 173, 0.84);font-weight: bold;">
        <%= @medical_certificate.patient.full_name %>  
      </label>
      <br/>
      <label style="font-size: 1rem;text-transform: uppercase;font-weight: bold;">
        Correo Electrónico:
      </label>
      <br/>
      <label style="font-size: 1rem;color: rgba(147, 159, 173, 0.84);font-weight: bold;">
        <%= @medical_certificate.patient.email %>  
      </label>
      <br/>

      <%= simple_form_for :mailer, url: users_path do |f| %>
        <%= f.input :email, as: :string, :label => "Correo Electrónico" %>
        <button type="button" class="btn btn-outline-primary">
          <i class="material-icons mr-1">email</i> Enviar
        </button>
      <% end %>
    </div>
    <div class="col-md-9">
      <iframe src="<%= medical_certificate_path(@medical_certificate.id, :format => "pdf") %>#view=FitH" style="right:0; top:0; bottom:0; width:100%;height: 75vh;background: rgb(50, 54, 57);"></iframe>
    </div>
  </div>
  
</div>

<div class="modal-footer">
  <div class="actions">
    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
      <i class="material-icons mr-1">close</i> Cerrar
    </button>
    <button type="button" class="btn btn-outline-primary">
      <i class="material-icons mr-1">print</i> Imprimir
    </button>
  </div>
</div>