config/routes.rb
Rails.application.routes.draw do
  resources :medical_certificates
  resources :personal_protection_entries
  resources :recipes
  resources :personal_protection_patients
  resources :personal_protections
  resources :company_processes
  resources :tasks
  resources :diagnostics
  resources :projects
  resources :commissions
  resources :work_centers
  resources :medical_services
  resources :risk_evaluations
  resources :risk_evaluation_risks
  resources :risks
  resources :risk_categories
  devise_for :users, controllers: { sessions: 'users/sessions' }
  match '/positions/diagram' => 'positions#diagram', :via => [:get, :post, :put]
  resources :medical_appointments do
    collection do
      get "today"
    end
  end
  resources :medical_records do
    collection do
      get "audits"
    end
    member do
      get "audit"
    end
  end
  resources :patient_records do 
    member do
      get "vaccines"
      get "recipes"
      get "laboratories"
      get "medical_history"
      get "medical_certificates"
    end
    resources :medical_checks do
      member do
        get "preview"
        get "result_file"
      end

    end
  end
  resources :medical_results, only: [:index, :show] do
    collection do
      get "distribution"
      get "diseases"
    end
  end
  resources :indicators, only: [:index] do
    collection do
      get "absenteeism"
    end
  end
  resources :medical_entries, only: [:index, :show, :new] do
    collection do
      get "register_values"
      get "list"
    end
  end
  resources :medical_profiles
  resources :exams
  resources :patients do
    collection do
      get "import_nl_patient"
      get "reports"
      get "print" 
    end
  end
  resources :areas
  resources :companies do
    collection do
      get "import_nl_source"
    end
  end
  resources :positions
  resources :users

  get 'risk_evaluations_details_dataset', to: 'risk_evaluations#get_dataset_details'
  get 'risk_evaluations_dataset', to: 'risk_evaluations#get_dataset'
  get 'risk_categories_dataset', to: 'risk_categories#get_dataset'
  get 'risks_dataset', to: 'risks#get_dataset'
  get 'projects_dataset', to: 'projects#get_dataset'
  get 'companies_dataset', to: 'companies#get_dataset'
  get 'commissions_dataset', to: 'commissions#get_dataset'
  get 'work_centers_dataset', to: 'work_centers#get_dataset'
  get 'exams_dataset', to: 'exams#get_dataset'
  get 'diagnostics_dataset', to: 'diagnostics#get_dataset'
  get 'personal_protections_dataset', to: 'personal_protections#get_dataset'
  get 'personal_protection_entries_dataset', to: 'personal_protection_entries#get_dataset'
  get 'positions_dataset', to: 'positions#get_dataset'
  get 'medical_profiles_dataset', to: 'medical_profiles#get_dataset'
  get 'patients_dataset', to: 'patients#get_dataset'
  get 'patient_records_dataset', to: 'patient_records#get_dataset'
  get 'medical_services_dataset', to: 'medical_services#get_dataset'
  get 'users_dataset', to: 'users#get_dataset'
  post 'save_current_company', to: 'companies#save_current_company'
  post 'get_exams_1', to: 'medical_profiles#get_exams_1'
  # Auto save methods
  post 'new_personal_history', to:'medical_records#new_personal_history'
  post 'remove_personal_history', to:'medical_records#remove_personal_history'

  root to: 'stack#index'
  get ':page' => 'stack#show', as: 'stack'

  mount ReportsKit::Engine, at: '/'
  
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_patient, :get_civil_states, only: [:index]

  before_action :set_medical_record, only: [:show, :audit, :edit, :update, :destroy]
  before_action :get_doctors, :get_patients, :get_ci_type, :get_positions, :get_companies, :get_areas, :get_medical_types, only: [:create, :new, :edit, :update, :index, :audits, :show, :audit]
  before_action :get_medical_status, only: [:index, :audits]
  before_action :get_personal_histories, :get_gender, :get_habits, 
                :get_lifestyles, :get_family_histories, :get_system_revisions, :get_vital_constants, 
                :get_exams, :get_diagnostics, :get_physical_exams, 
                :get_trauma_types, :get_trauma_curvature_types, only: [:show, :update, :audit, :index, :audits, :new, :create]

  respond_to :html

  def index
    @sidebar_rigth_app = true
    @medical_records = MedicalRecord.all

    if params["/medical_records"].present?
      if params["/medical_records"][:patient_id].present?
        @medical_records = @medical_records.where(:patient_id => params["/medical_records"][:patient_id])
        @patient_filter = true
        Rails.logger.info "=====>>>>@patient_filter: #{@patient_filter}"
      end

      if params["/medical_records"][:medical_type_id].present?
        @medical_records = @medical_records.where(:medical_type_id => params["/medical_records"][:medical_type_id])
        @medical_type_filter = true
      end

      if params["/medical_records"][:doctor_id].present?
        @medical_records = @medical_records.where(:doctor_id => params["/medical_records"][:doctor_id])
        @doctor_filter = true
      end

      if params["/medical_records"][:year].present?
        @medical_records = @medical_records.where('extract(year from date) = ?', params["/medical_records"][:year])
        @year_filter = true
      end

      if params["/medical_records"][:audit].present? && params["/medical_records"][:audit] == 'true'
        @medical_records = @medical_records.where(status: :finished)  
      end
    end
    
    @medical_records = @medical_records.to_a.group_by_day(&:date)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def audits
    @sidebar_rigth_app = true
    @medical_records = MedicalRecord.all

    if params["/medical_records"].present?
      if params["/medical_records"][:patient_id].present?
        @medical_records = @medical_records.where(:patient_id => params["/medical_records"][:patient_id])
        @patient_filter = true
        Rails.logger.info "=====>>>>@patient_filter: #{@patient_filter}"
      end

      if params["/medical_records"][:medical_type_id].present?
        @medical_records = @medical_records.where(:medical_type_id => params["/medical_records"][:medical_type_id])
        @medical_type_filter = true
      end

      if params["/medical_records"][:doctor_id].present?
        @medical_records = @medical_records.where(:doctor_id => params["/medical_records"][:doctor_id])
        @doctor_filter = true
      end

      if params["/medical_records"][:year].present?
        @medical_records = @medical_records.where('extract(year from date) = ?', params["/medical_records"][:year])
        @year_filter = true
      end

      if params["/medical_records"][:audit].present? && params["/medical_records"][:audit] == 'true'
        @medical_records = @medical_records.where(status: :finished)  
      end
    end
    
    @medical_records = @medical_records.to_a.group_by_day(&:date)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def load_records
    @medical_records = MedicalRecord.group_by_day(:created_at).count
  end

  def show
    @sidebar_rigth_app = true
    @patient = @medical_record.patient
    @medical_record.toxic_habit_ids = [1, 2, 3] unless @medical_record.toxic_habit_ids.any?
    @medical_record.lifestyle_ids = [1, 2, 2, 2] unless @medical_record.lifestyle_ids.any?
    @medical_record.family_history_ids = [1, 2, 3, 4, 5, 6, 7, 8] unless @medical_record.family_history_ids.any?
    @medical_record.system_revision_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] unless @medical_record.system_revision_ids.any?
    @medical_record.vital_constant_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9] unless @medical_record.vital_constant_ids.any?
    @medical_type_to_s = helpers.select_array(@medical_types, @medical_record.medical_type_id)
    # doctor could be nil on ecuamerican imported, then add current user
    if @medical_record.doctor.nil? && @medical_record.medical_type_id == 4
      @medical_record.update_attribute(:doctor_id, 2)
    end

    @medical_record.build_spe_ophthalmolytic unless @medical_record.spe_ophthalmolytic.present?

    if @patient.present? && @patient.position.present? && @patient.position.medical_profile.present?
      @medical_record.exam_ids = @patient.position.medical_profile.exam_ids unless @medical_record.exam_ids.any?
    end
    @medical_record.physical_exam_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40] unless @medical_record.physical_exam_ids.any?
    @available_sections = ('a'..'o').to_a
    if @medical_record.medical_type_id == 4
      @medical_type_to_s = @medical_record.exams.first.name
      if @medical_record.exams.first.code == '917'
        @available_sections = ['a','p','k','m']
      elsif @medical_record.exams.first.code == '931'
        @available_sections = ['a','b','q','k']
      end
    elsif @medical_record.medical_type_id == 5
      @available_sections = ['a','b','k']
    end

    respond_with(@medical_record)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def audit
    @sidebar_rigth_app = true

    if @medical_record.medical_type_id == 0
      @pdf_url_demo = "/pdfs/msp/inicial.pdf"
    elsif @medical_record.medical_type_id == 1
      @pdf_url_demo = "/pdfs/msp/periodica.pdf"
    elsif @medical_record.medical_type_id == 2
      @pdf_url_demo = "/pdfs/msp/reintegro.pdf"
    elsif @medical_record.medical_type_id == 3
      @pdf_url_demo = "/pdfs/msp/retiro.pdf"
    elsif @medical_record.medical_type_id == 4
      @pdf_url_demo = "/pdfs/msp/evaluacion.pdf"
    elsif @medical_record.medical_type_id == 5
      @pdf_url_demo = "/pdfs/msp/control.pdf"
    end

    respond_modal_with @medical_record
  end

  def new
    @medical_record = MedicalRecord.new
    @medical_record.medical_type_id = 1
    @medical_record.date = Time.now

    if params[:patient_id].present?
      Rails.logger.info "-====>>>>>>> params[:patient_id]: #{params.inspect}"
      @medical_record.patient = Patient.find(params[:patient_id])
      if @medical_record.patient && params[:position_id].present? 
        @patient = @medical_record.patient
        @patient.position_id = params[:position_id]
        @patient.save(:validate => false)
      end
    elsif params[:ci].present?
      Rails.logger.info "-====>>>>>>> on ci"
      patient = Patient.new
      patient.active = true
      patient.ci_type = 2
      patient.ci = params[:ci]
      patient.save(:validate => false)
      @medical_record.patient_id = patient.id
      Rails.logger.info "-====>>>>>>> @medical_record.patient.ci: #{@medical_record.patient.ci}"
    else
      @medical_record.patient = Patient.new
      @medical_record.patient.active = true
      @medical_record.patient.ci_type = 2
    end

    if @patient.present? && @patient.position.present? && @patient.position.medical_profile.present?
      @medical_record.exam_ids = @patient.position.medical_profile.exam_ids unless @medical_record.exam_ids.any?
    end

    respond_modal_with @medical_record
  end

  def edit
  end

  def create
    if params[:medical_record][:legacy_id].present?
      nl_api = NextLabApi.new(session[:import_credential_token])
      api_order = nl_api.get_api_orders(params[:medical_record][:legacy_id], 'order')
      tmp_order = OpenStruct.new(api_order.to_h)
      tmp_order[:date] = DateTime.parse tmp_order[:date]
      # Import doctor
      tmp_order.doctor = OpenStruct.new(api_order["doctor"].to_h)
        doctor = User.find_or_initialize_by(legacy_id: tmp_order.doctor["legacy_id"])
        unless doctor.id.present?
          doctor.name = tmp_order.doctor["nom_med"]
          doctor.email = tmp_order.doctor["email"].blank? ? "usuario_#{tmp_order.doctor["legacy_id"]}@import_nextlab.com" : tmp_order.doctor["email"]
          doctor.login = "usuario_#{tmp_order.doctor["legacy_id"]}"
          doctor.password = "usuario_#{tmp_order.doctor["legacy_id"]}"
          if doctor.valid?
            doctor.save
            doctor.add_role(:doctor)
          else
            Rails.logger.info "=============================================== DOCTOR.INSPECT"
            Rails.logger.info doctor.errors.messages.inspect
          end
        end
      # Import patient
      tmp_order.patient = OpenStruct.new(api_order["patient"].to_h)
        tmp_patient = api_order["patient"].to_h
        tmp_patient.delete("full_name")
        tmp_patient.delete("age")
        patient = Patient.find_or_initialize_by(tmp_patient)
        unless patient.id.present?
          patient.active = true
          patient.ci_type = 2
          patient.area = @areas.first
          patient.company_id = @company.id
          if patient.valid?
            patient.save
          else
            Rails.logger.info "=============================================== PATIENT.INSPECT"
            Rails.logger.info patient.errors.messages.inspect
          end
        end
      api_order["requests"].each do |request|
        exam = Exam.find_by(code: request["analisis"]["cod_ana"])
        if exam.nil?
          exam = Exam.new
          exam.code = request["analisis"]["cod_ana"]
          exam.name = request["analisis"]["des_ana"]
          exam.active = true
          exam.save if exam.valid?
        end
        # Prepare medical records

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/views/medical_records/_record_items.html.erb
<% if medical_records.any? %>
  <% if patient_filter.present? || status_filter.present? || medical_type_filter.present? || doctor_filter.present? || year_filter.present? %>
    <span class="badge badge-light">Filtrado por: </span>
  <% end %>
  <% if patient_filter.present? %>
    <span class="badge badge-secondary">
      EMPLEADO 
      <a id="patient_filter" class="remove-filter" href="#" onclick="remove_patient_filter()">x</a>
    </span>
  <% end %>
  <% if status_filter.present? %>
    <span class="badge badge-secondary">
      ESTADO 
      <a id="status_filter" class="remove-filter" href="#" onclick="remove_status_filter()">x</a>
    </span>
  <% end %>
  <% if medical_type_filter.present? %>
    <span class="badge badge-secondary">
      TIPO EVALUACIÓN 
      <a id="medical_type_filter" class="remove-filter" href="#" onclick="remove_medical_type_filter()">x</a>
    </span>
  <% end %>
  <% if doctor_filter.present? %>
    <span class="badge badge-secondary">
      DOCTOR 
      <a id="doctor_filter" class="remove-filter" href="#" onclick="remove_doctor_filter()">x</a>
    </span>
  <% end %>
  <% if year_filter.present? %>
    <span class="badge badge-secondary">
      AÑO 
      <a id="year_filter" class="remove-filter" href="#" onclick="remove_year_filter()">x</a>
    </span>
  <% end %>
  <% medical_records.each do |r| %>
    <p class="text-dark-gray d-flex align-items-center mt-3">
      <i class="material-icons icon-muted mr-2">event</i>
      <strong><%= r.first.strftime("%A, %-d %b %Y") %></strong>
    </p>
    <% r.last.each do |i| %>
      <div class="row align-items-center projects-item mb-1">
        <div class="col-sm-auto mb-1 mb-sm-0">
          <div class="text-dark-gray"><%= i.date.strftime("%I:%M %p") %></div>
        </div>
        <div class="col-sm">
          <div class='card m-0 <%= "medical_type_#{i.medical_type_id}" %>'>
            <div class="px-4 py-3">
              <!-- <a href="#" class="text-dark-gray"><%= select_array(@medical_types, i.medical_type_id) %></a>
              <i class="material-icons icon-muted icon-20pt ml-2">folder</i> -->
              <!-- <div class="d-flex align-items-center">
              </div> -->
              
              <div class="row align-items-center">
                <div class="col-md-12">
                  <div class="d-flex align-items-center">
                    <% if i.legacy_id.present? && !i.legacy_id.blank? %>
                      <% if i.edit? || i.comments? %>
                        <a href="<%= medical_record_path(i.id) %>" class="text-body"><strong class="text-15pt mr-2"><%= "##{i.id_to_s} - #{i.exams.first.name.upcase}" %> </strong></a>
                      <% else %>
                        <a class="text-body"><strong class="text-15pt mr-2"><%= "##{i.id_to_s} - #{i.exams.first.name.upcase}" %> </strong></a>
                      <% end %>
                    <% else %>
                      <a href="<%= medical_record_path(i.id) %>" class="text-body"><strong class="text-15pt mr-2"><%= "#{i.generate_code} - #{select_array(@medical_types, i.medical_type_id)}" %> </strong></a>
                    <% end %>
                    <% if i.finished? %>
                      <span class="badge badge-secondary">Finalizado</span>
                    <% else %>
                      <span class="badge badge-primary">Abierto</span>
                      <% if i.comments? || !i.comments.blank? %>
                        &nbsp;<span class="badge badge-danger">Tiene Novedades</span>
                      <% end %>
                    <% end %>
                    <span class="badge {{ badge_class }}"></span>
                  </div>
                </div>

                <div class="col-md-4">
                  <small class="text-dark-gray mr-2">Empleado</small>
                  <a href="<%= patient_path(i.patient.id) %>" class="d-flex align-items-center" data-modal="true">
                    <span class="avatar avatar-xxs avatar-online mr-2">
                      <%= show_avatar(i.patient) %>
                    </span>
                    <%= i.patient.full_name %>
                  </a>
                </div>

                <div class="col-md-4">
                  <small class="text-dark-gray mr-2">Puesto de trabajo</small>
                  <%- if i.patient.position.present? %>
                    <a href="<%= position_path(i.patient.position.id) %>" class="d-flex align-items-center"  data-modal="true">
                      <!-- <span class="avatar avatar-xxs avatar-online mr-2">
                        <%= show_avatar(i.patient) %>
                      </span> -->
                      <%= i.patient.position.name %>
                    </a>
                  <%- else %>
                    <%= t("label.blank") %>
                  <%- end %>
                  
                </div>

                <div class="col-md-4">
                  <small class="text-dark-gray mr-2">Doctor responsable</small>
                  <% if i.doctor.present? %>
                    <a href="<%= user_path(i.doctor) %>" class="d-flex align-items-center" data-modal="true">
                      <span class="avatar avatar-xxs avatar-online mr-2">
                        <%= show_avatar(i.doctor) %>
                      </span>
                      <%= i.doctor.name %>
                    </a>
                  <% else %>
                    Sin asignar
                  <% end %>
                  
                </div>

                

              </div>


            </div>
          </div>
        </div>
      </div>  
    <% end %>
  <% end %>
<% else %>
  <p class="text-dark-gray d-flex align-items-center mt-3">
    <i class="material-icons icon-muted mr-2">cancel</i>
    <strong>No existe resultados</strong>
  </p>
<% end %>

app/views/medical_records/_section_i.html.erb
<div class="card">
  <div class="card-header card-header-small bg-white">
    <h4 class="card-header__title"><div class="text-label" style="margin-bottom: 0"><span class="section_label"><%= secuence.upcase %>.</span> EXAMEN FÍSICO REGIONAL</div></h4>
  </div>
  <div class="card-body">

    <!-- Company -->
    <div class="row">
      <div class="col-md-12">

        <%- new_region_name = "" %>
        <%- old_region_name = "" %>
        
        <div class="row">
          <div class="col-md-4 fields" style="padding: 15px; border-bottom: 1px solid #ccc">
            <%= form.fields_for :medical_record_physical_exams, @medical_record.medical_record_physical_exams.sort_by(&:id) , :wrapper => false do |physical_exam_form| %>
              <%- new_region_name = physical_exam_form.object.region %> 
              
              <% if new_region_name != old_region_name && old_region_name != "" %>
                </div>
                <div class="col-md-4 fields" style="padding: 15px; border-bottom: 1px solid #ccc">
              <% end %>

              <div class="row">
                <div class="col-md-4">
                  <%= new_region_name if new_region_name != old_region_name %>
                  <%- old_region_name = new_region_name if new_region_name != old_region_name %>
                </div>
                <div class="col-md-6">
                  <%= physical_exam_form.object.physical_exam_id %>
                  <%= select_array(@physical_exams.map{|t| [t.name, t.id.to_s]}, physical_exam_form.object.physical_exam_id) %>
                </div>
                <div class="col-md-2">
                  <div class="custom-control custom-switch">
                    <%= physical_exam_form.check_box :active, :class => "custom-control-input" %>
                    <%= physical_exam_form.label :active, :class => "custom-control-label" %>
                  </div>
                </div>
              </div> 
            <% end %>
          </div>
          <div class="col-md-4 fields" style="padding: 15px; border-bottom: 1px solid #ccc"></div>
          <div class="col-md-4 fields" style="padding: 15px; border-bottom: 1px solid #ccc"></div>
        </div>
      </div>
    </div>

    <br/>
    <div class="row">
      <div class="col-md-12">
        <%= form.input :exam_description %>
      </div>
    </div>

  </div>
</div>

app/views/medical_records/_section_m.html.erb
<div class="card">
  <div class="card-header card-header-small bg-white">
    <h4 class="card-header__title"><div class="text-label" style="margin-bottom: 0"><span class="section_label"><%= secuence.upcase %>.</span> RECOMENDACIONES Y/O TRATAMIENTO</div></h4>
  </div>
  <div class="card-body">
    <!-- Company -->
    <div class="row">
      <div class="col-md-12">
        <%= form.input :recommendations %>
      </div>
    </div>
  </div>
</div>

app/views/medical_records/_section_s.html.erb
<div class="card">
  <div class="card-header card-header-small bg-white">
    <h4 class="card-header__title"><div class="text-label" style="margin-bottom: 0"><span class="section_label"><%= secuence.upcase %>.</span> ACTIVIDADES EXTRA LABORALES</div></h4>
  </div>
  <div class="card-body">
    <!-- Company -->
    <div class="row">
      <div class="col-md-12">
        <%= form.input :extra_labor_activities, label: false %>
      </div>
    </div>
  </div>
</div>

app/views/medical_records/audit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Auditoria Evaluación Médica</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= simple_form_for(@medical_record, remote: request.xhr?, html: { data: { modal: true } }) do |form| %>
  <input type="hidden" name="modal" value="1">
  <div class="modal-body">

    <% if false %>
      <iframe src="<%= result_file_patient_record_medical_check_path(@medical_record.patient_id , @medical_record.id, :format => "pdf") %>#view=FitH" style="right:0; top:0; bottom:0; width:100%;height: 70vh;background: rgb(50, 54, 57);"></iframe>
    <% end %>

    <iframe src="<%= @pdf_url_demo %>" style="right:0; top:0; bottom:0; width:100%;height: 65vh;background: rgb(50, 54, 57);"></iframe>

    <%= form.input :comments %>

  </div>



  <div class="modal-footer">
    <div class="actions">
      <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
        <i class="material-icons mr-1">close</i> Cerrar
      </button>
      

      <button type="submit" value="comments" name="medical_record[status]" class="btn btn-primary">
        <i class="material-icons mr-1">save</i> Guadar con Novedad
      </button>

      <button type="submit" value="audited" name="medical_record[status]" class="btn btn-success">
        <i class="material-icons mr-1">check</i> Terminar
      </button>

    </div>
  </div>
<% end  %>

app/views/medical_records/edit.html.erb
<h1>Editing Medical Record</h1>

<%= render 'form', medical_record: @medical_record %>

<%= link_to 'Show', @medical_record %> |
<%= link_to 'Back', medical_records_path %>

app/views/medical_records/index.html.erb
<div class="control-page">
  <div class="controls-list">
      <%= link_to "#", :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">arrow_upward</i>
        Exportar
      <% end %>
      <%= link_to new_medical_record_path, :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">add</i>
        Nuevo
      <% end %>
  </div>
</div>

<div class="container-fluid page__container pt-4">
  
  <!-- <div class="row">
    <div class="col-md-12">
      <div class="page__heading d-flex align-items-center">
        <div class="flex">
          <h3 class="m-0">Evaluaciones por Empleado</h3>
        </div>
      </div>
    </div>
  </div> -->

  <div class="row">
    <div class="col-md-12">
      <div class="card card-form d-flex flex-column flex-sm-row">
        <div class="card-form__body card-body-form-group flex">
          <%= simple_form_for(medical_records_path, remote: true, method: :get, html: { id: "load_records" }) do |f| %>
          <%= f.input :audit , as: :hidden, input_html: {value: params[:audit]} %>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="filter_name">Empleado</label>
                  <%= f.input :patient_id, collection: @all_patients, label: false, label_method: lambda { |p| "#{p.full_name_ci}"}, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="filter_name">Estado</label>
                  <%= f.input :status_id, collection: @medical_status, label: false, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="filter_buckets">Tipo Evaluación</label><br>
                <%= f.input :medical_type_id, collection: @medical_types, label: false, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="filter_name">Doctor</label>
                  <%= f.input :doctor_id, collection: @doctors, label: false, label_method: lambda { |p| "#{p.name}"}, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="filter_date">Año</label>
                <%= f.input :year, collection: 2010..2020, label: false, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
              </div>
            </div>
          </div>
            <%= f.submit "Send", id: "send_load_records", style: "display:none;" %>
          <% end %>
        </div>
        <button id="refresh" class="btn bg-white border-left border-top border-top-sm-0 rounded-top-0 rounded-top-sm rounded-left-sm-0"><i class="material-icons text-primary">refresh</i></button>
      </div>
      <div id="records_spinner" class="is-loading is-loading-lg">Loading content</div>
      <div id="container-timeline"></div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $( document ).ready(function() {
    $('select.select_2').select2({
      language: {
        noResults: function () {
          return "No se encontró resultados";
        }
      },
      placeholder: function(){
        $(this).data('placeholder');
      },
      containerCssClass: ':all:',
      theme: "bootstrap",
      dropdownParent: $('body')
    });
  });

  $(".date-selector").flatpickr({
    enableTime: false,
    dateFormat: "Y-m-d",
  });

  load_timeline();

  function load_timeline(){
    console.log("Load time line")
    $("#container-timeline").hide();
    $("#records_spinner").show();
    $("#send_load_records").click();
  }

  $(".select_2").change(function() {
    load_timeline();    
  });

  $("#refresh").click(function() {
    load_timeline();    
  });


  function remove_patient_filter(){
    $("#_medical_records_patient_id").prop("selectedIndex", 0);
    $("#_medical_records_patient_id").trigger('change');
  }

  function remove_status_filter(){
    $("#_medical_records_status_id").prop("selectedIndex", 0);
    $("#_medical_records_status_id").trigger('change');
  }

  function remove_medical_type_filter(){
    $("#_medical_records_medical_type_id").prop("selectedIndex", 0);
    $("#_medical_records_medical_type_id").trigger('change');
  }

  function remove_doctor_filter(){
    $("#_medical_records_doctor_id").prop("selectedIndex", 0);
    $("#_medical_records_doctor_id").trigger('change');
  }

  function remove_year_filter(){
    $("#_medical_records_year").prop("selectedIndex", 0);
    $("#_medical_records_year").trigger('change');
  }

  
</script>

app/views/medical_records/show.js.erb
console.log("saved!!!");