config/routes.rb
Rails.application.routes.draw do
  resources :medical_certificates
  resources :personal_protection_entries
  resources :recipes
  resources :personal_protection_patients
  resources :personal_protections
  resources :company_processes
  resources :tasks
  resources :diagnostics
  resources :projects
  resources :commissions
  resources :work_centers
  resources :medical_services
  resources :risk_evaluations
  resources :risk_evaluation_risks
  resources :risks
  resources :risk_categories
  devise_for :users, controllers: { sessions: 'users/sessions' }
  match '/positions/diagram' => 'positions#diagram', :via => [:get, :post, :put]
  resources :medical_appointments do
    collection do
      get "today"
    end
  end
  resources :medical_records do
    collection do
      get "audits"
    end
    member do
      get "audit"
    end
  end
  resources :patient_records do 
    member do
      get "vaccines"
      get "recipes"
      get "laboratories"
      get "medical_history"
      get "medical_certificates"
    end
    resources :medical_checks do
      member do
        get "preview"
        get "result_file"
      end

    end
  end
  resources :medical_results, only: [:index, :show] do
    collection do
      get "distribution"
      get "diseases"
    end
  end
  resources :indicators, only: [:index] do
    collection do
      get "absenteeism"
    end
  end
  resources :medical_entries, only: [:index, :show, :new] do
    collection do
      get "register_values"
      get "list"
    end
  end
  resources :medical_profiles
  resources :exams
  resources :patients do
    collection do
      get "import_nl_patient"
      get "reports"
      get "print" 
    end
  end
  resources :areas
  resources :companies do
    collection do
      get "import_nl_source"
    end
  end
  resources :positions
  resources :users

  get 'risk_evaluations_details_dataset', to: 'risk_evaluations#get_dataset_details'
  get 'risk_evaluations_dataset', to: 'risk_evaluations#get_dataset'
  get 'risk_categories_dataset', to: 'risk_categories#get_dataset'
  get 'risks_dataset', to: 'risks#get_dataset'
  get 'projects_dataset', to: 'projects#get_dataset'
  get 'companies_dataset', to: 'companies#get_dataset'
  get 'commissions_dataset', to: 'commissions#get_dataset'
  get 'work_centers_dataset', to: 'work_centers#get_dataset'
  get 'exams_dataset', to: 'exams#get_dataset'
  get 'diagnostics_dataset', to: 'diagnostics#get_dataset'
  get 'personal_protections_dataset', to: 'personal_protections#get_dataset'
  get 'personal_protection_entries_dataset', to: 'personal_protection_entries#get_dataset'
  get 'positions_dataset', to: 'positions#get_dataset'
  get 'medical_profiles_dataset', to: 'medical_profiles#get_dataset'
  get 'patients_dataset', to: 'patients#get_dataset'
  get 'patient_records_dataset', to: 'patient_records#get_dataset'
  get 'medical_services_dataset', to: 'medical_services#get_dataset'
  get 'users_dataset', to: 'users#get_dataset'
  post 'save_current_company', to: 'companies#save_current_company'
  post 'get_exams_1', to: 'medical_profiles#get_exams_1'
  # Auto save methods
  post 'new_personal_history', to:'medical_records#new_personal_history'
  post 'remove_personal_history', to:'medical_records#remove_personal_history'

  root to: 'stack#index'
  get ':page' => 'stack#show', as: 'stack'

  mount ReportsKit::Engine, at: '/'
  
end

app/controllers/medical_checks_controller.rb
class MedicalChecksController < ApplicationController
  before_action :set_patient, :get_civil_states, :get_blood_type, only: [:index, :show, :preview, :result_file]

  before_action :set_medical_record, only: [:show, :audit, :edit, :update, :destroy, :preview, :result_file]
  before_action :get_doctors, :get_patients, :get_ci_type, :get_positions, :get_companies, :get_areas, :get_medical_types, only: [:create, :new, :edit, :update, :index, :audits, :show, :audit]
  before_action :get_medical_status, only: [:index, :audits]
  
  before_action :get_personal_histories, :get_gender, :get_habits, 
                :get_lifestyles, :get_family_histories, :get_system_revisions, :get_vital_constants, 
                :get_exams, :get_diagnostics, :get_physical_exams, :get_profession, 
                :get_trauma_types, :get_trauma_curvature_types, only: [:show, :audit, :index, :new, :create]

  respond_to :html

  def index
    @sidebar_rigth_app = true

    @medical_records   = @patient.medical_records.where(:initial => false).order(date: :asc).to_a.group_by_year(&:date)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def audits
    @sidebar_rigth_app = true
    @medical_records = MedicalRecord.all

    if params["/medical_records"].present?
      if params["/medical_records"][:patient_id].present?
        @medical_records = @medical_records.where(:patient_id => params["/medical_records"][:patient_id])
        @patient_filter = true
        Rails.logger.info "=====>>>>@patient_filter: #{@patient_filter}"
      end

      if params["/medical_records"][:medical_type_id].present?
        @medical_records = @medical_records.where(:medical_type_id => params["/medical_records"][:medical_type_id])
        @medical_type_filter = true
      end

      if params["/medical_records"][:doctor_id].present?
        @medical_records = @medical_records.where(:doctor_id => params["/medical_records"][:doctor_id])
        @doctor_filter = true
      end

      if params["/medical_records"][:year].present?
        @medical_records = @medical_records.where('extract(year from date) = ?', params["/medical_records"][:year])
        @year_filter = true
      end

      if params["/medical_records"][:audit].present? && params["/medical_records"][:audit] == 'true'
        @medical_records = @medical_records.where(status: :finished)  
      end
    end
    
    @medical_records = @medical_records.to_a.group_by_day(&:date)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def load_records
    @medical_records = MedicalRecord.group_by_day(:created_at).count
  end

  def show
    @sidebar_rigth_app = true
    @patient = @medical_record.patient
    @medical_record.toxic_habit_ids = [1, 2, 3] unless @medical_record.toxic_habit_ids.any?
    @medical_record.lifestyle_ids = [1, 2, 2, 2] unless @medical_record.lifestyle_ids.any?
    @medical_record.family_history_ids = [1, 2, 3, 4, 5, 6, 7, 8] unless @medical_record.family_history_ids.any?
    @medical_record.system_revision_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] unless @medical_record.system_revision_ids.any?
    @medical_record.vital_constant_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9] unless @medical_record.vital_constant_ids.any?
    @medical_type_to_s = helpers.select_array(@medical_types, @medical_record.medical_type_id)
    # doctor could be nil on ecuamerican imported, then add current user
    if @medical_record.doctor.nil?
      @medical_record.update_attribute(:doctor_id, 2)
    end

    sections_control

    @initial_history = @medical_record.get_initial_history
    unless @medical_record.medical_record_accident_deseases.any?
      @medical_record.medical_record_accident_deseases = [
        MedicalRecordAccidentDesease.new(accident_type: 'Accidente'),
        MedicalRecordAccidentDesease.new(accident_type: 'Enfermedad')]
    end

    if @medical_record.exams.first && @medical_record.exams.first.code == '917'
      @medical_record.build_spe_ophthalmolytic unless @medical_record.spe_ophthalmolytic.present?
    end

    respond_with(@medical_record)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def audit
    @sidebar_rigth_app = true
    @patient = @medical_record.patient
    @medical_record.toxic_habit_ids = [1, 2, 3] unless @medical_record.toxic_habit_ids.any?
    @medical_record.lifestyle_ids = [1, 2, 2, 2] unless @medical_record.lifestyle_ids.any?
    @medical_record.family_history_ids = [1, 2, 3, 4, 5, 6, 7, 8] unless @medical_record.family_history_ids.any?
    @medical_record.system_revision_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] unless @medical_record.system_revision_ids.any?
    @medical_record.vital_constant_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9] unless @medical_record.vital_constant_ids.any?
    @medical_type_to_s = helpers.select_array(@medical_types, @medical_record.medical_type_id)
    # doctor could be nil on ecuamerican imported, then add current user
    if @medical_record.doctor.nil? && @medical_record.medical_type_id == 4
      @medical_record.update_attribute(:doctor_id, 2)
    end
    
    sections_control

    @initial_history = @medical_record.get_initial_history

    respond_with(@medical_record)

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def new
    @medical_record = MedicalRecord.new
    @medical_record.medical_type_id = 1
    @medical_record.date = Time.now

    if params[:patient_record_id].present?
      Rails.logger.info "-====>>>>>>> params[:patient_record_id]: #{params.inspect}"
      @medical_record.patient = Patient.find(params[:patient_record_id])
      if @medical_record.patient && params[:position_id].present? 
        @patient = @medical_record.patient
        @patient.position_id = params[:position_id]
        @patient.save(:validate => false)
      end
    elsif params[:ci].present?
      Rails.logger.info "-====>>>>>>> on ci"
      patient = Patient.new
      patient.active = true
      patient.ci_type = 2
      patient.ci = params[:ci]
      patient.save(:validate => false)
      @medical_record.patient_id = patient.id
      Rails.logger.info "-====>>>>>>> @medical_record.patient.ci: #{@medical_record.patient.ci}"
    else
      @medical_record.patient = Patient.new
      @medical_record.patient.active = true
      @medical_record.patient.ci_type = 2
    end

    # Set current doctor
    @medical_record.doctor_id = 2

    if @patient.present? && @patient.position.present? && @patient.position.medical_profile.present?
      @medical_record.exam_ids = @patient.position.medical_profile.exam_ids unless @medical_record.exam_ids.any?
    end

    respond_modal_with @medical_record
  end

  def edit
  end

  def preview
    # PdfWatermark.conbinate_watermark_pdf(Rails.root.join(odt_file_path.gsub(".odt", ".pdf")), Rails.root.join(watermark_file_path))  
    @certificate = params[:certificate].present?

    Rails.logger.info "===== = == = @certificate: #{@certificate}"

    if @medical_record.medical_type_id == 0
      @pdf_url_demo = "/pdfs/msp/inicial.pdf"
    elsif @medical_record.medical_type_id == 1
      @mo_result = true
    elsif @medical_record.medical_type_id == 2
      @pdf_url_demo = "/pdfs/msp/reintegro.pdf"
    elsif @medical_record.medical_type_id == 3
      @pdf_url_demo = "/pdfs/msp/retiro.pdf"
    elsif @medical_record.medical_type_id == 4
      @pdf_url_demo = "/pdfs/msp/evaluacion.pdf"
    elsif @medical_record.medical_type_id == 5
      @pdf_url_demo = "/pdfs/msp/control.pdf"
    end

    @can_finish = params[:on_edit].present?
    
    respond_to do |f|
      f.html {respond_modal_with @medical_record}
      f.js {respond_modal_with @medical_record}
      f.pdf {send_data MedicalRecord.print_data(@medical_record, @certificate), filename:'medical_record.pdf', type: "application/pdf", disposition: :inline}
    end
    
  end

  def result_file

    if @medical_record.exams.first && @medical_record.exams.first.code == '917'
      jasper_name      = "spe_ophthalmolytic.jasper"
    else
      jasper_name      = "evaluation_template.jasper"
    end

    evaluation_file  = "evaluation_#{@medical_record.id}"

    respond_to do |format|
      format.pdf {send_doc(@medical_record.to_xml, '/evaluation', jasper_name, evaluation_file, "pdf")}
      format.xml {render xml: @medical_record.to_xml}
    end
  end

  def create
    @medical_record = MedicalRecord.create(medical_record_params)
    # @medical_record.date = Time.now unless @medical_record.valid?
    respond_modal_with @medical_record, location: @medical_record.valid? ? patient_record_medical_check_path(@medical_record.patient.id,@medical_record.id) : patient_record_medical_checks_path(@medical_record.patient.id)
  end

  def update
    if params[:medical_record][:status] == "comments" && params[:medical_record][:comments] == ""
      @medical_record.errors.add(:comments, "No debe estar vacío")
      #@redirect = true
      #@redirect_url = audit_medical_record_path(@medical_record)
    else
      @medical_record.update(medical_record_params)

      @redirect = @medical_record.finished?
      @redirect_url = medical_records_path
    end
    Rails.logger.info "===========================================> @medical_record.errors"
    Rails.logger.info @medical_record.errors.messages.inspect
    # respond_with(@medical_record)
    
    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def destroy
    @medical_record.destroy
    respond_with(@medical_record)
  end

  # Auto save methods
  def new_personal_history
    if params[:personal_history].present?
      personal_history_name = params[:personal_history][:name]
      medical_record_id = params[:personal_history][:medical_record_id]
      personal_history = PersonalHistory.create(:name => personal_history_name) if personal_history_name.present?
      MedicalRecordPersonalHistory.create(:medical_record_id => medical_record_id, :personal_history_id => personal_history.id)
    end
    render json: { personal_history_id: personal_history.id}
  end

app/views/medical_checks/index.html.erb
<div class="control-page">
  <div class="controls-list">
      <%= link_to patient_records_path, :class => "ml-3 float-l" do %>
        <i class="material-icons">arrow_back</i>
        Lista Fichas Medicas
      <% end %>
      <%= link_to new_patient_record_medical_check_path, :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">add</i>
        Nuevo
      <% end %>
  </div>
</div>

<div class="container-fluid page__container pt-4">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Consultas Médicas</h4>
        </div>
        <div class="card-body">
          <div class="row align-items-center mb-2">
            <div class="col-sm-12 align-self-center">
              <div class="btn-group">
                <button type="button" class="btn btn-light medical-type-btn" data-id="all">Todos</button>
                <% @medical_types.each do |medical_type| %>
                  <button type="button" class="btn btn-light medical-type-btn" style="color:<%= medical_type[2] %>;" data-id="<%= medical_type[1] %>"><%= medical_type[0].gsub('Medicina Ocupacional - ', '') %></button>
                <% end %>
              </div>
            </div>
          </div>
          <% if @medical_records.any? %>
            <% @medical_records.each do |r| %>
              <p class="text-dark-gray d-flex align-items-center mt-3">
                <i class="material-icons icon-muted mr-2">event</i>
                <strong><%= r.first.strftime("%Y") %></strong>
              </p>
              <% r.last.each do |i| %>
                <div class="row align-items-center projects-item mb-1 medical-type-item-<%= i.medical_type_id %>">
                  <div class="col-sm-auto mb-1 mb-sm-0">
                    <div class="text-dark-gray"><%= i.date.strftime("%-d %b %I:%M %p") %></div>
                  </div>
                  <div class="col-sm">
                    <div class='card m-0 <%= "medical_type_#{i.medical_type_id}" %>' style="border-left:3px solid <%= @medical_types.select {|mt| mt[1].to_i == i.medical_type_id }.first[2] %>">
                      <div class="px-4 py-3">

                        
                        <div class="row align-items-center">
                          <div class="col-md-7">
                            <div class="d-flex align-items-center">


                              <% if i.legacy_id.present? && !i.legacy_id.blank? %>
                                <% if i.edit? || i.comments? %>
                                  <a href="<%= patient_record_medical_check_path(@patient.id, i.id) %>" class="text-body"><strong class="text-15pt mr-2"><%= i.record_name %> </strong></a>
                                <% elsif i.audited? || i.finished? %>
                                  <strong class="text-15pt mr-2 text-muted"><%= i.record_name %> </strong>
                                <% else %>
                                  <a class="text-body"><strong class="text-15pt mr-2"><%= i.record_name %> </strong></a>
                                <% end %>
                              <% else %>

                                <% if i.audited? || i.finished? %>
                                  <strong class="text-15pt mr-2 text-muted"><%= i.record_name %> </strong>
                                <% else %>
                                  <a href="<%= patient_record_medical_check_path(@patient.id, i.id) %>" class="text-body"><strong class="text-15pt mr-2"><%= i.record_name %> </strong></a>
                                <% end %>

                              <% end %>

                              <% if i.finished? %>
                                <span class="badge badge-secondary">
                                  Finalizado
                                  <i class="material-icons icon-16pt">check</i>
                                </span>
                              <% elsif i.audited? %>
                                <span class="badge badge-success">
                                  Aprobado
                                  <i class="material-icons icon-16pt">lock</i>
                                </span>
                              <% else %>
                                <span class="badge badge-primary">
                                  Abierto
                                  <i class="material-icons icon-16pt ml-1">edit</i>
                                </span>
                                <% if i.comments? || !i.comments.blank? %>
                                  &nbsp;<span class="badge badge-danger">Tiene Novedades</span>
                                <% end %>
                              <% end %>

                            </div>

                          </div>

                          <div class="col-md-5" style="text-align: right;">
                            <% if i.medical_certificates.any? %>
                              <%= link_to '<i class="material-icons icon-16pt">content_paste</i> P. Médico'.html_safe , medical_certificate_path(i.medical_certificates.last.id), class: "btn btn-sm btn-info",  data: { modal: true } %>
                            <% end %>

                            <% if i.recipes.any? %>
                              <%= link_to '<i class="material-icons icon-16pt">content_paste</i> Receta'.html_safe , recipe_path(i.recipes.last.id), class: "btn btn-sm btn-info ml-1",  data: { modal: true } %>
                            <% end %>

                            <% if i.medical_type_id <= 3 %>
                              <%= link_to '<i class="material-icons icon-16pt">picture_as_pdf</i> Aptitud'.html_safe , preview_patient_record_medical_check_path(@patient.id , i.id, :certificate => true), class: "btn btn-sm btn-primary ml-1",  data: { modal: true } %>
                            <% end %>

                            <%= link_to '<i class="material-icons icon-16pt">picture_as_pdf</i> Ver'.html_safe , preview_patient_record_medical_check_path(@patient.id , i.id), class: "btn btn-sm btn-success ml-1",  data: { modal: true } %>

                          </div>

                          <div class="col-md-4">
                            <small class="text-dark-gray mr-2">Empleado</small>
                            <a href="<%= patient_path(i.patient.id) %>" class="d-flex align-items-center" data-modal="true">
                              <span class="avatar avatar-xxs avatar-online mr-2">
                                <%= show_avatar(i.patient) %>
                              </span>
                              <%= i.patient.full_name %>
                            </a>
                          </div>

                          <div class="col-md-4">
                            <small class="text-dark-gray mr-2">Puesto de trabajo</small>
                            <%- if i.patient.position.present? %>
                              <a href="<%= position_path(i.patient.position.id) %>" class="d-flex align-items-center"  data-modal="true">
                                <!-- <span class="avatar avatar-xxs avatar-online mr-2">
                                  <%= show_avatar(i.patient) %>
                                </span> -->
                                <%= i.patient.position.name %>
                              </a>
                            <%- else %>
                              <br/>
                              <%= t("label.blank") %>
                            <%- end %>
                            
                          </div>

                          <div class="col-md-4">
                            <small class="text-dark-gray mr-2">Doctor responsable</small>
                            <% if i.doctor.present? %>
                              <a href="<%= user_path(i.doctor) %>" class="d-flex align-items-center" data-modal="true">
                                <span class="avatar avatar-xxs avatar-online mr-2">
                                  <%= show_avatar(i.doctor) %>
                                </span>
                                <%= i.doctor.name %>
                              </a>
                            <% else %>
                              Sin asignar
                            <% end %>
                          </div>


                        </div>
                      </div>
                    </div>
                  </div>
                </div>  
              <% end %>
            <% end %>
          <% else %>
            <p class="text-dark-gray d-flex align-items-center mt-3">
              <i class="material-icons icon-muted mr-2">cancel</i>
              <strong>No existe resultados</strong>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.medical-type-btn').click(function(e) {
    e.preventDefault();
    let current_medical_type_id = $(this).data('id');
    let medical_type_class = ".medical-type-item-" + current_medical_type_id;
    let medical_record_count = $('.projects-item').length;
    if (current_medical_type_id == 'all') {
      $('.projects-item').fadeIn();
    } else {
      $('.projects-item').each(function(i, e){
        $(e).fadeOut();
        if (i+1 === medical_record_count) {
          console.log('Showing: ' + medical_type_class);
          $(medical_type_class).fadeIn();
        }
      });
    }
  })
</script>

app/views/medical_checks/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Nueva Evaluación</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', medical_record: @medical_record %>

app/views/medical_checks/show.html.erb
<div class="control-page">
  <div class="controls-list">
      <%= link_to patient_record_medical_checks_path(@patient.id), :class => "ml-3 float-l" do %>
        <i class="material-icons">arrow_back</i>
        Consultas Medicas
      <% end %>

      <%= link_to new_medical_certificate_path(:patient_id => @patient.id, :medical_record_id => @medical_record.id), :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">add</i>
        Permiso Médico
      <% end %>

      <%= link_to new_recipe_path(:patient_id => @patient.id, :medical_record_id => @medical_record.id), :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">add</i>
        Receta
      <% end %>
  </div>
</div>
<div class="container-fluid page__container medical_record_form" id="page_container_work">
  <%= simple_nested_form_for(@medical_record, remote: true, html: { method: :put }) do |form| %>
    <%#= form.input :status, as: :hidden, input_html: {value: form.object.status} %>
    <div class="row" id="to_sticky-container">
      
      <div class="col-md-12" id="to_sticky">
        <div class="page__heading d-flex align-items-center mt-2 mb-0 p-0">
          
          <div class="flex">
            <h3 class="m-0"><%= @medical_type_to_s %></h3>
            <p style="margin-bottom: 0" class="text-muted show-sticky">
              <%= "#{@patient.full_name_ci}, #{@patient.company.name} - #{@patient.position.present? ? @patient.position.name : ''}" %>
            </p>
            <span class="badge badge-light" id="counterdown">Guardado automático: 01:00</span>
          </div>

          <% if @medical_record.medical_certificates.any? %>
            <%= link_to '<i class="material-icons icon-16pt">content_paste</i> P. Médico'.html_safe , medical_certificate_path(@medical_record.medical_certificates.last.id), class: "btn btn-info ml-3",  data: { modal: true } %>
          <% end %>

          <% if @medical_record.recipes.any? %>
            <%= link_to '<i class="material-icons icon-16pt">content_paste</i> Receta'.html_safe , recipe_path(@medical_record.recipes.last.id), class: "btn btn-info ml-3",  data: { modal: true } %>
          <% end %>
                    
          <button id="auto_save_from" class="btn btn-primary ml-3">
            <i class="material-icons icon-16pt">save</i>
            Guardar
          </button>

          <%= link_to '<i class="material-icons icon-16pt">picture_as_pdf</i> Vista Previa'.html_safe , preview_patient_record_medical_check_path(@patient.id , @medical_record.id, :on_edit => true), class: "btn btn-success ml-3",  data: { modal: true } %>          

        </div>

        <div class="progress" style="width: 100%; height: 2px">
          <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:0%;height:2px;background-color: <%= @medical_types.select {|mt| mt[1].to_i == @medical_record.medical_type_id }.first[2] %>"></div>
        </div>
      </div>
    </div>

    <% unless @medical_record.comments.blank? %>
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-small bg-white">
              <h4 class="card-header__title">
                <div class="text-label" style="margin-bottom: 0">NOVEDADES</div>
              </h4>
            </div>
            <div class="card-body">
              <!-- Company -->
              <div class="row">
                <div class="col-md-12">
                  <div class="alert alert-warning" role="alert">
                    <strong>Registrado por: </strong>Administrador del sistema
                    <br/>
                    <%= @medical_record.comments %>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-12">
        <% alph = ('a'..'v').to_a %>
        <% @available_sections.each_with_index do |section, index| %>
          <div id="section_container_<%= section %>">
            <%= render '/medical_records/section_'+section, form: form, secuence: alph[index], current_section: section %>
          </div>
        <% end %>
      </div>
    </div>
    <%= form.submit 'Teminar Evaluación', :id => "auto_save_record",  name: "medical_record[status]", value: :edit, :class => "btn btn-success ml-3", :style => "display: none;"%>
    <%= form.submit 'redirect', :id => "save_record_redirect", name: "medical_record[status]", value: :finished, :class => "btn btn-success ml-3", :style => "display: none;" %>
  <% end %>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $(".progress-bar").css("width", "0%")
    var medical_record_id = <%= @medical_record.id %>;
    $('select.select_personal_history_ids').select2({
      tags: true,
      tokenSeparators: [','],
      createTag: function (tag) {
        return {
            id: tag.term,
            text: tag.term,
            tag: true,
            newTag: true
        };
      }
    }).on('select2:select', function (evt) {
        var select2Element = $(this);
        if (evt.params.data.newTag == true){
          $.ajax({
            type: "POST",
            url: "/new_personal_history",
            data: {
              personal_history: {
                name: evt.params.data.text,
                medical_record_id: medical_record_id
              }
            },
            success: function(data) {
              option_selected = select2Element.find('option[value="'+evt.params.data.text+'"]')
              option_selected.attr("value", data.personal_history_id);              
              return false;
            },
            error: function(data) {
              return alert("Problemas con la conexión del sistema");
            }
          });
        }
    }).on('select2:unselect', function (evt) {
        // console.log(evt);
        // console.log(evt.params.data.element.value);
        $.ajax({
          type: "POST",
          url: "/remove_personal_history",
          data: {
            personal_history: {
              personal_history_id: evt.params.data.element.value,
              medical_record_id: medical_record_id
            }
          },
          success: function(data) {
            console.log(data)
            return false;
          },
          error: function(data) {
            return alert("Problemas con la conexión del sistema");
          }
        });
    });

    $('select.select_2').select2({
      language: {
        noResults: function () {
          return "No se encontró resultados";
        }
      },
      placeholder: function(){
        $(this).data('placeholder');
      },
      containerCssClass: ':all:',
      theme: "bootstrap"
    });

    $(".date-selector").flatpickr({
      enableTime: false,
      dateFormat: "Y-m-d",
    });    

  });
</script>

<script type="text/javascript">
  var total = 60000;
  var counter = 0;
  var counterdown = total / 1000;
  // Auto Save
  var auto_save = setInterval(function () {
    // $(".edit_medical_record").submit();
    $(".progress-bar").css("width", "0%");
    $("#auto_save_record").click();
    counter = 0;
    counterdown = total / 1000;
    $("#counterdown").html("Cambios guardados");
  },total); 

  var myInterval = setInterval(function () {
    ++counter;
    --counterdown;
    seg = total / 1000;
    procentage = (counter * 100) / seg;
    $(".progress-bar").css("width", procentage + "%");
    $("#counterdown").html("Guardado automatico: " + secondsTimeSpanToHMS(counterdown));
  }, 1000);


  function secondsTimeSpanToHMS(s) {
    var h = Math.floor(s/3600); //Get whole hours
    s -= h*3600;
    var m = Math.floor(s/60); //Get remaining minutes
    s -= m*60;
    // return h+":"+(m < 10 ? '0'+m : m)+":"+(s < 10 ? '0'+s : s); //zero padding on minutes and seconds
    return (m < 10 ? '0'+m : m)+":"+(s < 10 ? '0'+s : s); //zero padding on minutes and seconds
  }

  // to stop the counter
  // clearInterval(myInterval);

  // clearInterval(auto_save);

  $( "#auto_save_from" ).click(function(e) {
    e.preventDefault();
    $("#auto_save_record").click();
    counter = 0
    counterdown = total / 1000;
    $("#counterdown").html("Cambios guardados");
  });


</script>