config/routes.rb
Rails.application.routes.draw do
  resources :medical_certificates
  resources :personal_protection_entries
  resources :recipes
  resources :personal_protection_patients
  resources :personal_protections
  resources :company_processes
  resources :tasks
  resources :diagnostics
  resources :projects
  resources :commissions
  resources :work_centers
  resources :medical_services
  resources :risk_evaluations
  resources :risk_evaluation_risks
  resources :risks
  resources :risk_categories
  devise_for :users, controllers: { sessions: 'users/sessions' }
  match '/positions/diagram' => 'positions#diagram', :via => [:get, :post, :put]
  resources :medical_appointments do
    collection do
      get "today"
    end
  end
  resources :medical_records do
    collection do
      get "audits"
    end
    member do
      get "audit"
    end
  end
  resources :patient_records do 
    member do
      get "vaccines"
      get "recipes"
      get "laboratories"
      get "medical_history"
      get "medical_certificates"
    end
    resources :medical_checks do
      member do
        get "preview"
        get "result_file"
      end

    end
  end
  resources :medical_results, only: [:index, :show] do
    collection do
      get "distribution"
      get "diseases"
    end
  end
  resources :indicators, only: [:index] do
    collection do
      get "absenteeism"
    end
  end
  resources :medical_entries, only: [:index, :show, :new] do
    collection do
      get "register_values"
      get "list"
    end
  end
  resources :medical_profiles
  resources :exams
  resources :patients do
    collection do
      get "import_nl_patient"
      get "reports"
      get "print" 
    end
  end
  resources :areas
  resources :companies do
    collection do
      get "import_nl_source"
    end
  end
  resources :positions
  resources :users

  get 'risk_evaluations_details_dataset', to: 'risk_evaluations#get_dataset_details'
  get 'risk_evaluations_dataset', to: 'risk_evaluations#get_dataset'
  get 'risk_categories_dataset', to: 'risk_categories#get_dataset'
  get 'risks_dataset', to: 'risks#get_dataset'
  get 'projects_dataset', to: 'projects#get_dataset'
  get 'companies_dataset', to: 'companies#get_dataset'
  get 'commissions_dataset', to: 'commissions#get_dataset'
  get 'work_centers_dataset', to: 'work_centers#get_dataset'
  get 'exams_dataset', to: 'exams#get_dataset'
  get 'diagnostics_dataset', to: 'diagnostics#get_dataset'
  get 'personal_protections_dataset', to: 'personal_protections#get_dataset'
  get 'personal_protection_entries_dataset', to: 'personal_protection_entries#get_dataset'
  get 'positions_dataset', to: 'positions#get_dataset'
  get 'medical_profiles_dataset', to: 'medical_profiles#get_dataset'
  get 'patients_dataset', to: 'patients#get_dataset'
  get 'patient_records_dataset', to: 'patient_records#get_dataset'
  get 'medical_services_dataset', to: 'medical_services#get_dataset'
  get 'users_dataset', to: 'users#get_dataset'
  post 'save_current_company', to: 'companies#save_current_company'
  post 'get_exams_1', to: 'medical_profiles#get_exams_1'
  # Auto save methods
  post 'new_personal_history', to:'medical_records#new_personal_history'
  post 'remove_personal_history', to:'medical_records#remove_personal_history'

  root to: 'stack#index'
  get ':page' => 'stack#show', as: 'stack'

  mount ReportsKit::Engine, at: '/'
  
end

app/models/medical_entry.rb
class MedicalEntry < ApplicationRecord
  belongs_to :medical_service, optional: true
  belongs_to :patient
  belongs_to :company

  belongs_to :medical_service

  def exam
    Exam.find_by(code: self.cod_ana)
  end

  def id_to_s
  	self.id.to_s.rjust(5, "0")
  end
end

app/controllers/medical_entries_controller.rb
class MedicalEntriesController < ApplicationController
  respond_to :html
  before_action :get_api_doctors, :get_areas, :get_positions

  def list
    @sidebar_rigth_app = true
    @from_date = params[:from_date] || Time.now
    @to_date = params[:to_date] || Time.now

    nl_api = NextLabApi.new(session[:import_credential_token])

    if params[:nro_order].present?
      @orders = [nl_api.get_api_orders(params[:nro_order].strip, 'order')]
    elsif params[:ci].present?
      @orders = nl_api.get_api_orders(params[:ci].strip, 'patient')
    else
      @orders = nl_api.get_api_orders("from_date=#{@from_date}&to_date=#{@to_date}", 'date_range')
    end
    
    # Group by Patient
    patients = []
    patients = @orders.group_by{|h| h["patient"]["ci"]} if @orders.any?

    @order_by_patients = []
    orders = []
    full_name = ""

    patients.each do |patient_orders|
      Rails.logger.info "======>>>> patient_orders: #{patient_orders.last}"
      orders = []  
      full_name = ""
      patient_orders.last.each do |order|
        Rails.logger.info "======>>>> order: #{order}"
        full_name = order["patient"]["full_name"]

        requests = []
        laboratory = false

        order["requests"].each do |request|
          medical_record = MedicalRecord.where(:nro_ord => order["nro_order"], :cod_ana => request["exam"]["cod_ana"]).last
          if request["rnd_pet"] == true
            requests << {
              :name => request["exam"]["nom_exam"],
              :code => request["exam"]["cod_ana"],
              :type => "record",
              :status => medical_record.present? ? medical_record.status : "none",
              :pdf_url => medical_record.present? ? medical_record.pdf_demo : nil
            }
          elsif request["rnd_pet"] == false
            laboratory = true
          end
        end

        if laboratory
          requests << {
            :name => "Laboratorio",
            :type => "laboratory",
            :status => "audited",
            :pdf_url => nil
          }
        end

        orders << {
          :nro_ord => order["nro_order"],
          :date => order["date"],
          :requests => requests
        }
      end

      patient = {
        :patient => {
          :full_name => full_name,
          :orders => orders
        }
      }

      @order_by_patients << patient  

    end
  end

  def index
    @sidebar_rigth_app = true
    api_orders = Array.new
    @medical_entries = Array.new

    nl_api = NextLabApi.new(session[:import_credential_token])
    
    if params[:order].present?
      # Call order service by Nro
      @order = OpenStruct.new(nl_api.get_api_orders(params[:order], 'order').to_h)
      @active_services = MedicalService.where(active: true).where('company_id IS NULL OR company_id = ?', @company.id).order(:name)

      Rails.logger.info "========> @order: #{@order.inspect}"
      company = Company.find_or_initialize_by(legacy_id: @order.source["code"]) if @order.source.present?
      if company 
        company.name = @order.source["name"]
        company.code = @order.source["code"]
        company.save(validate: false)
      end

      # Add Laboratorio Item and save results
      # Remove results related with Laboratorio
      @requests = []
      item = 1
      lab_exits = false

      # import patient from order
      patient = Patient.find_or_initialize_by(legacy_id: @order.patient["legacy_id"]) if @order.patient.present?
      if patient 
        Rails.logger.info "===========> Patient: #{@order.patient.inspect}"
        patient.ci = @order.patient["ci"]
        patient.ci_type = 2
        patient.name = @order.patient["name"]
        patient.name_1 = @order.patient["name_1"]
        patient.last_name = @order.patient["last_name"]
        patient.last_name_1 = @order.patient["last_name_1"]
        patient.gender = @order.patient["gender"]
        patient.birth_date = @order.patient["birth_date"]
        patient.email = @order.patient["email_pac"]
        patient.company_id = company.id if company.present?
        patient.active = true
        patient.save(validate: false)
      end

      if @order.present? && @order.requests.present? && @order.requests.any?

        lab_requests = []

        @order.requests.each do |r|
          if r["rnd_pet"] == true
            medical_entry = MedicalEntry.find_by(nro_ord: @order.nro_order, cod_ana: r["exam"]["cod_ana"])
            @requests << {
                idx: item,
                des_ana: r["exam"]["nom_exam"],
                cod_ana: r["exam"]["cod_ana"],
                sts_pet: r["sts_pet"],
                service: medical_entry.present? && medical_entry.medical_service.present? ? medical_entry.medical_service.name : nil,
                created_at: medical_entry.present? ? medical_entry.created_at : nil,
                updated_at: medical_entry.present? ? medical_entry.updated_at : nil,
                pdf_url: medical_entry.present? ? medical_entry_path(medical_entry) : new_medical_entry_path(nro_ord: @order.nro_order, cod_pac: @order.patient["legacy_id"], cod_ana: r["exam"]["cod_ana"], des_ana: r["exam"]["nom_exam"], cod_pet: r["cod_pet"]),
                is_saved: medical_entry.present?
              }
            item += 1
          elsif r["rnd_pet"] == false 
            lab_requests << r["exam"]
          end
        end

        if lab_requests.any?
          @lab_request = {
            idx: 0,
            des_ana: "Laboratorio",
            service: lab_requests,
            sts_pet: "",
            created_at: nil,
            updated_at: nil,
            pdf_url: nil,
            is_saved: false
          }
        end
      end
    end

    respond_to do |f|
      f.html {}
      f.js
    end
  end

  def show
    @medical_entry = MedicalEntry.find(params[:id])
    respond_modal_with @medical_entry
  end

  def register_values
    nro_order = params[:nro_order]
    nl_api = NextLabApi.new(session[:import_credential_token])
    @order = OpenStruct.new(nl_api.get_api_orders(nro_order, 'order').to_h)

    patient = Patient.find_or_initialize_by(legacy_id: @order.patient["legacy_id"])

    Rails.logger.info "==>> @order.requests: #{@order.requests}" 
    @order.requests.each do |r|
      if r["rnd_pet"] == false
        r["exam"]["determinations"].each do |det|
          Rails.logger.info "==>> det: #{det}"
          ep = ExamPatient.where(:patient_id => patient.id, :determination_id => det["cod_det"].to_i).last
          
          if !ep.present?
            ep = ExamPatient.new
          end
          exam = Exam.find_by_code(r["exam"]["cod_ana"])
          
          ep.exam_id    = exam.id if exam.present? 
          
          ep.patient_id = patient.id
          ep.determination_id = det["cod_det"].to_i
          ep.determination = det["nom_det"]
          ep.result = det["res_det"]
          ep.unit = det["uni_det"]
          ep.ref_value = det["val_ref"]
          ep.nro_ord = nro_order
          ep.active = true

          Rails.logger.info "==>> ep: #{ep.inspect}"
          ep.save

        end
      end
    end
    
  end

  def new
    patient = Patient.find_by(legacy_id: params[:cod_pac]).id
    @medical_entry = MedicalEntry.new
    @medical_entry.nro_ord = params[:nro_ord]
    @medical_entry.cod_ana = params[:cod_ana]
    @medical_entry.patient_id = patient
    @medical_entry.doctor_id = nil
    @medical_entry.medical_service_id = params[:service_id]
    @medical_entry.company_id = @company.id
    @medical_entry.created_by_id = current_user.id
    exam = Exam.find_by(code: params[:cod_ana])
    if exam.nil?
      exam = Exam.new
      exam.code = params[:cod_ana]
      exam.name = params[:des_ana]
      exam.active = true
      exam.save if exam.valid?
    end
    if @medical_entry.save
      # CREATE Medical Record
      @medical_record = MedicalRecord.find_or_initialize_by(legacy_id: params[:cod_pet])
      unless @medical_record.id.present?
        if @medical_entry.medical_service.id <= 3
          @medical_record.medical_type_id = @medical_entry.medical_service.id - 1
        else
          @medical_record.medical_type_id = 4
        end
        @medical_record.date = Time.now
        @medical_record.nro_ord = params[:nro_ord]
        @medical_record.cod_ana = params[:cod_ana]
        @medical_record.patient_id = patient
        @medical_record.doctor_id = nil
        @medical_record.company_id = @company.id
        if @medical_record.valid?
          @medical_record.save
        else
          Rails.logger.info "=============================================== MEDICAL_RECORD"
          Rails.logger.info @medical_record.errors.messages.inspect
        end
        if @medical_record.id.present?
          MedicalRecordExam.find_or_create_by(medical_record_id: @medical_record.id, exam_id: exam.id)
        end
      end
    else
      Rails.logger.info "=============================================== MEDICAL_ENTRY"
      Rails.logger.info @medical_entry.errors.messages.inspect
    end


    respond_modal_with @medical_entry
  end

  
end

app/views/medical_entries/_entry_items.html.erb
<% if order.nro_order.present? %>
  <div class="row">

    <div class="col-md-12 mb-2" style="color: #51A7C5">    
      <i class="mr-1 material-icons">person</i>
      <strong>Información del Paciente</strong>
    </div>
    
    <div class="col-md-4 mb-2">
      <div class="text-label mb-0">Paciente</div>
      <strong><%= order.patient["full_name"] %></strong>
    </div>

    <div class="col-md-4 mb-2">
      <div class="text-label mb-0">CI</div>
      <%= order.patient["ci"] %>
    </div>
    <div class="col-md-4 mb-2">
      <div class="text-label mb-0">Edad</div>
      <%= order.patient["age"] %>
    </div>

    <div class="col-md-4 mb-2">
      <div class="text-label mb-0">Sexo</div>
      <%= order.patient["gender"] == 1 ? "Masculino" : order.patient["gender"] == 2 ? "Femenino" : "No definido" %>
    </div>

    <div class="col-md-4 mb-2">
      <div class="text-label mb-0">Medico</div>
      <strong><%= order.doctor["nom_med"] %></strong>
    </div>

    <div class="col-md-4 mb-2">
      <div class="text-label mb-0">Origen</div>
      <strong><%= order.source["name"] %></strong>
    </div>
  </div>


  <div class="row">


    <div class="col-md-12 mb-2" style="color: #51A7C5">
      <i class="mr-1 material-icons">local_hospital</i>
      <strong>Valoraciónes de Especialidades</strong>
    </div>

    <div class="col-md-12">
      <div class="table-responsive mb-2" style="border: 1px solid #eee;">
        <table class="table simple-table mb-0 thead-border-top-0">
            <thead>
                <tr class="bg-light">
                    <th>#</th>
                    <th>Análisis</th>
                    <th>Servicio</th>
                    <th>Estado</th>
                    <th>Creado en</th>
                    <th>Control</th>
                </tr>
            </thead>
            <tbody>
              <% if @requests.any? %>
                <% @requests.each do |r| %>
                  <tr>
                    <form>
                      <td><%= r[:idx] %></td>
                      <td><%= "#{r[:cod_ana]} #{r[:des_ana]}" %></td>

                      <td class="service">
                        <% if r[:cod_ana].present? && r[:cod_ana] != "1095" && r[:cod_ana] != "1098" && r[:cod_ana] != "1101" %>
                        
                          <%= r[:service].present? ? r[:service] : collection_select('medical_entry', "medical_service_id", @active_services.map { |ms| ms.exam.code == r[:cod_ana] ? ms : nil}.compact, :id, :name, {prompt: true}, {class: 'select_2', :style => "width: 100%;"}) %>
                        
                        <% else %>  

                        <% end %>
                      </td>
                      <td><%= r[:sts_pet] %></td>
                      <td><%= r[:created_at].strftime(@date_time_format) if r[:created_at] %></td>
                      <td>
                        <% if r[:is_saved] %>
                          <a href="<%= r[:pdf_url] %>" class="btn btn-dark btn-block" data-modal="true" >
                            <i class="material-icons mr-1">print</i> Orden
                          </a>
                        <% else %>
                          <a href="<%= r[:pdf_url] %>" class="create_entry btn btn-primary btn-block" confirm-text="Esta seguro(a) de generar orden?" data-modal="true" >
                            <i class="material-icons mr-1">open_in_new</i> Orden
                          </a>
                        <% end %>
                      </td>
                    </form>
                  </tr>
                <% end %>
              <% else %>
                <tr>
                  <td colspan="7">
                    <p class="text-dark-gray align-items-center mt-1 mb-1" style="text-align: center;">
                      <i class="material-icons icon-muted mr-2">cancel</i>
                      <strong>No existe resultados</strong>
                    </p>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>

    <% if @lab_request %>

      <div class="col-md-12 mb-2" style="color: #51A7C5">    
        <i class="mr-1 material-icons">featured_play_list</i>
        <strong>Informe de Laboratorio</strong>
      </div>

      <div class="col-md-9">
        <% if @lab_request[:service] && @lab_request[:service].any? %>
          <div class="table-responsive mb-2" style="border: 1px solid #eee;">
            <table class="table simple-table mb-0 thead-border-top-0">
              <tr class="text-muted">
                <td>
                  <strong>DETERMINACIÓN</strong>
                </td>
                <td>
                  <strong>RESULTADO</strong>
                </td>
                <td>
                  <strong>UNIDAD</strong>
                </td>
                <td>
                  <strong>VAL REFERENCIA</strong>
                </td>
              </tr>
              <% @lab_request[:service].each do |r| %>
                <tr>
                  <td colspan="4">
                    <strong><%= "#{r["cod_ana"]} #{r["nom_exam"]}" %></strong>
                  </td>
                </tr>
                <% r["determinations"].each do |dt| %>
                    <tr>
                      <td>
                        <%= dt["nom_det"] %>
                      </td>

                      <td>
                        <%= dt["res_det"]%>
                      </td>
                      
                      <td>
                        <%= dt["uni_det"] %>
                      </td>
                      <td>
                        <%= dt["val_ref"] %>
                      </td>
                    </tr>
                <% end %>
              <% end %>

            </table>
          </div>
        <% else %>

        <% end %>
        
      </div>

      <div class="col-md-3">
        <div class="text-muted mb-2">Si desear registrar resultados del Paciente</div>
        
        <%= link_to "<i class='material-icons mr-1'>open_in_new</i> Registar".html_safe, register_values_medical_entries_path(:nro_order => order.nro_order), class: "btn btn-primary btn-block", remote: true %>
      </div>
    <% end %>

  </div>
<% else %>
  <p class="text-dark-gray align-items-center mt-1 mb-1" style="text-align: center;">
    <i class="material-icons icon-muted mr-2">cancel</i>
    <strong>No existe resultados</strong>
  </p>

<% end %>
<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  })
  $('select.select_2').select2({
    language: {
      noResults: function () {
        return "No se encontró resultados";
      }
    },
    placeholder: function(){
      $(this).data('placeholder');
    },
    containerCssClass: ':all:',
    theme: "bootstrap"
  });
  $('select.select_2').on('select2:select', function (e) { 
    let create_entry = $(this).parent().parent().find('.create_entry');
    let new_url = addParameter(create_entry.prop('href'), "service_id", e.params.data.id);
    create_entry.prop('href', new_url);
  });
</script>

app/views/medical_entries/_list_orders.html.erb
<div class="row">
  <div class="col-md-4">
		<% if orders.any? %>
			<ul class="list-group">
				<% orders.each do |order_by_patient| %>
					<li class="list-group-item d-flex align-items-center" style="padding: 10px">
						<div class="">
							<strong>
								<i class="material-icons">person</i>
								<%= order_by_patient[:patient][:full_name] %>		
							</strong>	
						
							<% order_by_patient[:patient][:orders].each do |order| %>	
								<div class="mt-2 mb-2" style="margin-left: 20px; color: #51A7C5">
									<i class="material-icons">merge_type</i>
									<%= order[:nro_ord] %>
								</div>
								<% order[:requests].each do |request| %>
									<div style="margin-left: 20px; font-weight: normal;" class="mb-1">
										<% if request[:type] == "record" %>
											<i class="material-icons">local_hospital</i>
										<% elsif request[:type] == "laboratory" %>
											<i class="material-icons">featured_play_list</i>
										<% end %>

										<% if request[:pdf_url].present? %>
											<%= link_to request[:name], "#", :onclick => "load_pdf('#{request[:pdf_url]}#view=FitH'); return false;" %>
										<% else %>
											<%= request[:name] %>
										<% end %>
										

										<% if request[:status] == "finished" %>
											<span class="badge badge-secondary"><i class="material-icons icon-16pt">check</i></span>
										<% elsif request[:status] == "audited" %>
											<span class="badge badge-success"><i class="material-icons icon-16pt">lock</i></span>
										<% elsif request[:status] == "none" %>
											<span class="badge badge-secondary"><i class="material-icons icon-16pt">block</i></span>
										<% else %>
											<span class="badge badge-primary"><i class="material-icons icon-16pt ml-1">edit</i></span>
										<% end %>

									</div>
								<% end %>
							<% end %>	

						</div>
					</li>
				<% end %>
			</ul>
		<% else %>
			<div class="text-muted">Sin Registros</div>
		<% end %>
	</div>

	<div class="col-md-8">
    <div id="pdf_object" style="height: 65vh; background-color: #f8f9fc; text-align: center; border: 1px solid #e3e6f0; overflow: hidden; border-radius: 3px;">
      <img src="/images/pdf-preview.png" style="width: 20%; top: 25vh; position: relative; opacity: 0.3;">
    </div>
  </div>
</div>

<script type="text/javascript">
  function load_pdf(url){
    $("#pdf_object").html("<iframe style='width: 100%; height: 100%' src="+ url +"> </iframe>")
  }
</script>

app/views/medical_entries/index.html.erb
<div class="control-page">
  <div class="controls-list">
      <%= link_to "#", :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">compare_arrows</i>
        Comprobar conexión
      <% end %>
  </div>
</div>
<div class="container-fluid page__container pt-4">
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Ingresos por orden NextLab</h4>
        </div>
        <div class="card-body button-list mb-2">
          <%= simple_form_for(medical_entries_path, remote: true, method: :get, html: { id: "load_records" }) do |f| %>
            <div class="row">
              <div class="col-md-12">
              
                <div class="form-group numeric required medical_entries_order">
                  <label class="form-control-label numeric required" for="order">Orden Nro NEXTLAB <abbr title="required">*</abbr></label>
                  <input class="form-control numeric numeric required" type="number" step="any" name="[order]" id="_medical_entries_order">
                </div>
                

              </div>
              <div class="col-md-6">
                <%= button_tag type: 'submit', id: "send_load_order", :class => 'btn btn-secondary btn-block', autocomplete: "off", :onclick => "$('#order').css('opacity', '0.5').css('pointer-events','none') ;", data: { disable_with: "..."} do %>
                  <i class="fas fa-search fa-sm text-white-50"></i> Buscar
                <% end %>
              </div>
              <div class="col-md-6">
                <%= f.button :button, '<i class="fas fa-eraser fa-sm text-white-50"></i> Borrar'.html_safe, id: "reset_print_order", :type => 'reset', :class => 'btn btn-secondary btn-block' %>
              </div>
            </div>
            <hr/>
            <strong>Usuario: </strong><br/>
            <%= current_user.name %>
            <br/>
            <strong>IP: </strong><br/>
            <%= Rails.env.development? ? "127.0.0.1" : request.remote_ip %>
          <% end %>  
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Datos de la orden</h4>
        </div>

        <div class="card-body button-list mb-2">
          <div id="container-order-entry">
            <img class="navbar-brand-icon mb-2" src="/images/ecua-american-logo.png" style="width: 100%; opacity: .3" alt="Stack">
          </div>
        </div>
        
      </div>
    </div>

  </div>

  <div class="mb-5"></div>
</div>

<script type="text/javascript">
  $(document).on("ajax:beforeSend", "#load_records", function() {
    $("#container-timeline").hide();
    $("#records_spinner").show();
  });

  $(".select_2").change(function() {
    $("#refresh_results").click();
  });
</script>

app/views/medical_entries/index.js.erb
$("#records_spinner").hide();
$("#container-order-entry").html("<%= escape_javascript(render partial: 'entry_items', locals: { order: @order } ) %>"); 
$("#container-order-entry").show();

app/views/medical_entries/list.html.erb
<div class="control-page">
  <div class="controls-list">
      <%= link_to "#", :class => "ml-3", data: { modal: true } do %>
        <i class="material-icons">compare_arrows</i>
        Comprobar conexión
      <% end %>
  </div>
</div>
<div class="container-fluid page__container pt-4" style="max-width: 100%">

  <div class="row">
    <div class="col-md-12">
      <%= simple_form_for(list_medical_entries_path, remote: true, method: :get, html: { id: "load_records" }) do |f| %>
        <div class="card card-form d-flex flex-column flex-sm-row">
        
          <div class="card-form__body card-body-form-group flex">
        
            <div class="row">

              <div class="col-sm-auto">
                <div class="form-group">
                  <label for="filter_name">Nro Orden</label>
                  <input id="nro_order" name="nro_order" type="text" class="form-control" placeholder="Orden NextLab">
                </div>
              </div>

              <div class="col-sm-auto">
                <div class="form-group">
                  <label for="filter_name">Cédula</label>
                  <input id="ci" type="text" name="ci" class="form-control" placeholder="Ingresar CI">
                </div>
              </div>

              <div class="col-sm-auto">
                <div class="form-group" style="width: 200px;">
                  <label for="filter_date">Desde</label>
                  <input id="from_date" type="text" name="from_date" class="form-control date-selector" placeholder="Seleacionar" value="<%= @from_date %>">
                </div>
              </div>

              <div class="col-sm-auto">
                <div class="form-group" style="width: 200px;">
                  <label for="filter_date">Hasta</label>
                  <input id="to_date" type="text" name="to_date" class="form-control date-selector" placeholder="Seleacionar" value="<%= @to_date %>">
                </div>
              </div>

              

              <!-- <div class="col-sm-auto">
                <div class="form-group">
                  <label for="filter_buckets">Empresa/Origen</label><br>
                  <select id="filter_buckets" class="custom-select" style="width: 150px;">
                    <option value="all">Any</option>
                    <option value="1">Deployed</option>
                    <option value="2">Concept</option>
                    <option value="3">Wireframe</option>
                  </select>
                </div>
              </div> -->

            </div>
          
          </div>
          <button class="btn bg-white border-left border-top border-top-sm-0 rounded-top-0 rounded-top-sm rounded-left-sm-0"><i class="material-icons text-primary">refresh</i></button>
        
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">
            Lista de Ingresos
            
            <div id="records_spinner" class="is-loading is-loading-lg" style="display: none; float: right; width: 16px; height: 16px;">Loading content</div>

          </h4>
        </div>
        <div class="card-body button-list mb-2">
          <div id="container-list-orders">
            <img class="navbar-brand-icon mb-2" src="/images/ecua-american-logo.png" style="width: 100%; opacity: .3" alt="Stack">
          </div>
        </div>
      </div>
    </div>


  </div>

  <div class="mb-5"></div>
</div>

<script type="text/javascript">
  $(document).on("ajax:beforeSend", "#load_records", function() {
    $("#container-timeline").hide();
    $("#records_spinner").show();
  });

  $(".select_2").change(function() {
    $("#refresh_results").click();
  });

  $(".date-selector").flatpickr({
    enableTime: false,
    dateFormat: "Y-m-d",
  });
</script>

app/views/medical_entries/list.js.erb
$("#records_spinner").hide();
$("#container-list-orders").html("<%= escape_javascript(render partial: 'list_orders', locals: { orders: @order_by_patients } ) %>");
$("#container-order-entry").show();

app/views/medical_entries/new.html.erb
<%= render 'print_order' %>

app/views/medical_entries/register_values.js.erb
alert("Resultados Registrados!")

app/views/medical_entries/show.html.erb
<%= render 'print_order' %>